### ISSUE TITLE
The new android 7.0 fs has an unreadable filesystem root

### ISSUE THREAD

**Issue by kpinc** [Coolcord/Squeez#8]
Hi,

I've Android 7.0 on a Nexus 5x.  Squeeze seems to be useless because the root of the filesystem (/) is not readable.  Hence, no directories show and navigation is impossible.

Perhaps you could change the initial directory to "/sdcard"?

**Comment by Coolcord** [comment]
If you'd like to update Squeez to support the latest Android OS, you're free to do so, and I can merge it in.

I'm not working on Squeez anymore, so I won't be making any changes myself.

**Comment by kpinc** [comment]
On Thu, 01 Dec 2016 12:13:58 -0800
Coolcord <notifications@github.com> wrote:

> If you'd like to update Squeez to support the latest Android OS,
> you're free to do so, and I can merge it in.

If you'd like to try the attached patch, feel free.
I haven't done Java in decades, and haven't tested
the patch.

Regards,

Karl <kop@meme.com>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein
